### ISSUE TITLE
Submit batch from watched directory

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#10]
### Description 
As a system, I want to pick up a batch for processing from a directory I am watching.

### Done Looks Like
- Write a rake tasks that looks in some specified place on disk, and start a new job if valid manifest files are found

- A file deposited in a specific location will be picked up and processed by the application
- This location is a URI—Avalon manifest files could be on a local filesystem, in S3, etc.
- All subdirectories of the watched directory are searched for valid submission files
- If a valid submission file is found, it is picked up and batch processing begins

**Comment by afred** [comment]
@joncameron Are you talking here about fetching the raw data from an external data store (i.e. S3) or the local filesystem, or a network share, etc?

**Comment by joncameron** [comment]
@afred I think all of the above. Someone on the Avalon side who's more familiar with the AWS stuff might be able to say more, but this should be applicable for our main cases—POSIX filesystem paths and Amazon cloud. I'm not as sure that this needs to cover every URI in the universe, especially things that aren't over HTTP.

**Comment by cjcolvar** [comment]
I think we could start by writing a rake task that takes the inputs for a batch (batch_type, source_location, submitter_email, and admin_set_id) and kicks off the batch via `BatchRunner.new(batch).run`.  From there we could write a task that scans a directory and kicks off the process for any batch found and finally have a cronjob call this scanning task.  This last part (scanning and cronjob) might make the most sense living within a specific implementation (so avalon-bundle).
@afred @davidschober @joncameron @sroosa Thoughts?

**Comment by sroosa** [comment]
@cjcolvar that makes sense to me, especially, splitting the last part into a specific implementation.

**Comment by yingfeng-iu** [comment]
Can we define "valid manifest file" in more detail? I assume the scanning code will not read or parse the file (that should be done by the batch reader), but just look at file extension and decide if it's valid? what are the valid extensions to include?

**Comment by singlesoliloquy** [comment]
@afred Can we close this?
