### ISSUE TITLE
Example Batches

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#11]
### Avalon
Example Manifest with Assets: http://www.avalonmediasystem.org/downloads/DemoFixturesBatch.tar.gz
Manifest: [Demo_Manifest.xlsx](https://github.com/samvera-labs/hyrax-batch_ingest/files/2376331/Demo_Manifest.xlsx)

### Done looks like
- [ ] WGBH provides an AMS publicly available example of AMS batch, i.e. a zip full of PBCore files.

**Comment by sroosa** [comment]
AMS samples: [AMS_Ingest_Samples.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54626d326426c20200ef8e46/125516c66e82c728ace21e0d46c9b9a91cab8dae8afaab7c975cfd84254334316546b3397f8fe62bab0021435a0d47ae17585710f8fcdc7fa1b13c70885909ebd43c0b26d42103eee9dc4be05ce36ade0d97bcae8b45cae93826e1828a4f3a1d0d1d8cf64f78.zip)

**Comment by davidschober** [comment]
Moved files to shared folder https://northwestern.app.box.com/folder/53578791759
