### ISSUE TITLE
Error Reporting / Error Handling

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#13]
### Description
Error reporting needs to be defined.

### Questions
- What is the level of granularity?
  - Errors are reported per batch item. Each element or attribute that is invalid is reported. It would be better if the value which was not expected was reported in addition to the raw line number in the file.

- How are errors listed when files are being processed?
  - An item is completely read through for each of its values and all errors present are compiled. If a single object had multiple errors, for example, they would all be represented in the error message available to the user; processing would not stop on the first error and skip to the next batch item. This will allow users to identify each issue and correct them in full before resubmitting.

- How to Treat Child Objects
   - If a child object contains errors and cannot be created, the parent item fails in full as well.

**Comment by davidschober** [comment]
This was discussed by virtue of other issues. TODO write up the final issues for refinement.

**Comment by davidschober** [comment]
We will have nice errors for the most common errors (required fields, badly formed csv, etc), for the rest we will dump verbose errors. 

Common Errors From DONUT: 

this is a list of the common batch ingest errors we have with Donut https://gist.github.com/jenyoung/867e9d17e60c527fca660b5ba449ca31
