### ISSUE TITLE
Submit batch by uploading through UI

### ISSUE THREAD

**Issue by sroosa** [samvera-labs/hyrax-batch_ingest#18]
### Description: 
As an AMS submitter, I can submit a batch from my local file system through the UI

### Considerations: 
- The submitter will be a logged in user, so that will give the system the information about who's submitting, rather than it being in a SIP or Avalon-style manifest file. 
- The user sets additional parameters through drop down menu
- The user uploads the file from local system

### Done Looks Like:
- Button on the batch list (dashboard) to submit a new batch
- A modal appears upon button select, which present users with:
   - User can select what type of SIP they are submitting (drop-down menu)
   - User can browse their file system and select a file to upload
   - User can set the Admin Set that the batch will be uploaded into (some users may only have access to one, but some will have access to many)
   - User can add other shared values for all records being ingested, as configured per application, per SIP (see comments for examples).
   - File type validation is performed against the file—if it does not match with the SIP type, the modal remains open and displays a message to the user that informs them of the correct file type to use
- Configurable option to have the button appear or not (specified in application configuration file)

**Comment by sroosa** [comment]
Mock up:
![Screen Shot 2018-10-24 at 11.06.36 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54626d326426c20200ef8e46/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f76b7191a379ee0c2b57415c48bc30254d58eeb9cb74fce36f34985619e883645d22c63545a8bdd74bb806ba20894a87b0b9db1892fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe14e5ca7153467e277376e0a.png)

**Comment by mcwhitaker** [comment]
@joncameron The idea of using a UI similar to this for starting a batch from Box or Globus using browseEverything has been considered very useful for Avalon so I think we need to have a story on the board for that. I understand that this UI option is beyond "feature parity with Avalon 6", so its priority may be low at this point, but I would prefer not to lose track of the suggested option.

**Comment by sroosa** [comment]
AAPB's AMS will need a few shared values to be added to a few of the SIP types. 

When ingesting a zipped file of PBCore Description Document xml files, users should be able to insert a single value for Location and Holding Organization to be added to all instantiations, if no value already exists in the source xml files.

When ingesting a zipped file of PBCore Digital Instantiation xml files, users should be able to insert a single value for Location and Holding Organization to be added to all instantiations, if no value already exists in the source xml files.

**Comment by sroosa** [comment]
@afred notice we did add back the idea of reading some data from a shared source,  just like you were talking about. but for AMS, we only want to do it for select fields that we can configure, so the user can input that shared data in while they are doing the upload through the UI.
