### ISSUE TITLE
Monitoring batch process progression

### ISSUE THREAD

**Issue by sroosa** [samvera-labs/hyrax-batch_ingest#19]
### Description:

On an item detail page for a batch, I will be able to see the status of items within a batch. At this phase we expect the user to do a page refresh to get updates. (extra points for push notifications):

## Done looks like

For each batch item in a batch indication / status for:

- initiated
- working 
- completed (with link to object created)
- error (with error trapped)

**Comment by mcwhitaker** [comment]
@davidschober  - could we get the screenshot for this?

**Comment by afred** [comment]
no screenshot.. but I found [the code in donut that decides which icons to use](https://github.com/nulib/donut/blob/7a9058690459f5e08da846e4e907a513471bc069/app/helpers/application_helper.rb#L47-L52).

It's using font-awesome characters which is pretty typical.
