### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/hyrax-batch_ingest#4]
Determine needs and create mockups of a dashboard to report details of batches and filter to find specific batches.

### Reporting
- Information on validation errors (header not present, metadata field not found etc.)

### Questions
- Do uploaded files for batch need to be stored? (As in, storing the manifest file itself in the database indefinitely for future retrieval).

### Interface
- Batches are displayed in a table with each row corresponding to an individual batch
- Each batch corresponds to an individual manifest file
- The Job ID field is hyperlinked to a detail page for that batch
- The detail page lists each child object created

depends on #14.

**Comment by davidschober** [comment]
@cjcolvar do you mean uploaded manifests and assets? I think as a first pass, we can have cleanup be manual.

**Comment by joncameron** [comment]
NU's batch status interface:

### Overview

![screen shot 2018-09-05 at 12 51 40 pm](https://user-images.githubusercontent.com/4803230/45118219-877bb700-b11d-11e8-8f21-2687f2df871d.png)

### Batch job view some errors, some green

![screen shot 2018-09-05 at 12 52 21 pm](https://user-images.githubusercontent.com/4803230/45118247-982c2d00-b11d-11e8-9bd6-7ffc86ffa14d.png)

**Comment by cjcolvar** [comment]
depends on #14.
