### ISSUE TITLE
Reporting on batch status

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/hyrax-batch_ingest#5]
Determine information and metrics to report on a batch object, successful or errored.  Possible information: current state, errors, # of objects created, total disk space used, ids of created objects, processing time, etc.  Possibly similar information for each batch item.

### Details
- Each row of the dashboard corresponds to a single top level item (asset, AV work)
- Each job gets a unique ID
- Submitter Name
- Original manifest filename
- Date submitted
- Status
  - Completed
  - Error
  - Pending
  - In Progress

depends on #14.

**Comment by davidschober** [comment]
NU's batch status interface:

### Overview

![screen shot 2018-09-05 at 12 51 40 pm](https://user-images.githubusercontent.com/4803230/45118219-877bb700-b11d-11e8-8f21-2687f2df871d.png)

### Batch job view some errors, some green

![screen shot 2018-09-05 at 12 52 21 pm](https://user-images.githubusercontent.com/4803230/45118247-982c2d00-b11d-11e8-9bd6-7ffc86ffa14d.png)

**Comment by cjcolvar** [comment]
depends on #14.
