### ISSUE TITLE
As a User I Can View Certain Batches

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#51]
### Description
Permissions need to be established. 
Managers can view all batches of Admin Sets they manage.
Depositors can view only batches they created. 

### Done Looks Like
Manager of an Admin Set can see a batch for the Admin Set that someone else created.
Depositor of an Admin Set can see a batch they created, but cannot see a batch that someone else created.

**Comment by yingfeng-iu** [comment]
The description uses the term "view", i wonder if we also need to check the permission for manager/depositor to create batch for a certain admin set. will that be achieved by ability here, or is that part of validation in the reader?

**Comment by cjcolvar** [comment]
@yingfeng-iu  
1. I think the validation should be in the ability but where and when exactly it is checked I haven't formulated a strong opinion yet (reader, model validation, or controller/cron job).
2. I'm pretty sure we can always depend on the email being able to resolve a user entry/id.  I'm doing it in the avalon ingester to instantiate an ability object: https://github.com/samvera-labs/avalon-bundle/blob/batch_ingest/app/services/hyrax/batch_ingest/audiovisual_work_item_ingester.rb#L7 .  I don't think we assume that the submitter email is the `current_user` so when doing web uploads of batches we could get into an odd case where the user uploading the batch doesn't match the submitter email.  But I think the permission checks that you're adding here have so far been centered around the REST interaction and that adding the ability for # 1 above will make it so we can handle the odd case as well.
 
I'd like to hear @afred's opinion on these questions too.

**Comment by yingfeng-iu** [comment]
For batch from dropbox, we won't know who actually dropped the manifest there, all we know is the submitter email in the manifest. The reader shall validate that field is not empty and is valid. when our script to fetch the manifest from dropbox process the file and create batch, the ability authorization will happen then, and i guess the script needs to populate current user by getting the user id form the submitter email.

For batch created from UI, i think there shall be some validation on upon submit to check if the submitter email match the current user, if not an error shall be prompted. The ability will check if the current user has the permission to create batch for the specified admin set.  I'm not sure which happens first, the validdation or the authorization.

**Comment by yingfeng-iu** [comment]
3. For Batch index, I'm debating on following options: 1) allow any user to perform index, and if he doesn't have permission to see any existing batch, nothing will be listed; 2) allow user to perform index only if he can perform show on at least one admin set among all admin sets (or, 3) among the existing batch admin sets). I'm leaning towards 1) for simplicity; if we do 2) or 3), we will end up going through admin sets twice when we select those he can show.

4. For permission on destroy, should we follow similar logic as view, i.e manager of admin set can destroy any batch of the admin set; depositor of a batch can only destroy the batch he created?

**Comment by cjcolvar** [comment]
My opinions on these questions:
3. I think # 2.  Not all users can see the dashboard and only certain users can see certain features within the dashboard.  I think we'd want to allow any admin set participant to see the batch UI but not for anyone else. #74 says that only users who have the rights to view a batch should see the link to the index.
4. I don't think we need to worry about destroy yet.

**Comment by yingfeng-iu** [comment]
Thanks Chris. I've updated the logic accordingly. Now I have a new issue when writing tests for Ability, the part where user's email is used to decide whether a batch is created by him. My current logic is as follows:
          # depositor of a batch can only show/cancel the batch created by himself
          can [:show, :destroy], Hyrax::BatchIngest::Batch do |batch|
            current_user == ::User.find_by(email: batch.submitter_email)
          end
However, in tests when I create user or batch, the email is auto assigned by sequence. I'm not sure how to populate the email with a specified value. To overcome this, I can also change the above logic, instead of comparing user, i can just compare the email as follows:
          can [:show, :destroy], Hyrax::BatchIngest::Batch do |batch|
            current_user.email == batch.submitter_email
          end
then I can mock the getter for email. If this sounds right, I just need to verify one thing: is user and his email a 1:1 relationship? if so this 2nd option shall work; otherwise it may not.

**Comment by cjcolvar** [comment]
I prefer the second approach since it is simpler and avoids a database query.  I think either approach assumes that email addresses are unique per user and I think that is a fine assumption to make.
As for the testing, I don't think you would need to mock anything.  You should be able to assign the submitter email to a batch:
```
let(:user) { FactoryBot.create(:user) }
let(:batch) { FactoryBot.create(:batch, submitter_email: user.email) }
```
or grab the email that is auto-assigned and use that to create the user:
```
let(:batch) { FactoryBot.create(:batch) }
let(:user) { FactoryBot.create(:user, email: batch.submitter_email) }
```

**Comment by yingfeng-iu** [comment]
great, that's what i'm doing.
