### ISSUE TITLE
NU Batch Code Investigation and Move to hyrax-batch_ingest

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#7]
## Description

As we start to work on the batch ingestion plugin, investigate the work from NU that we can 'borrow'. Hopefully we will be able to take the work/concepts and make it more generic in nature.

## Done looks like 
- investigate DONUT work
- Document what we can borrow
- create issues as necessary. 

## References

Core NU batch:

https://github.com/nulib/donut/tree/master/app/batch

There are also views and models within the application that should be investigated.

**Comment by afred** [comment]
Work described in this ticket will go on individual, more specific tickets.
