### ISSUE TITLE
Verification of Batch

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#9]
###
As a system, I want to validate submitted manifest files against an agreed upon format and schema.

**Comment by afred** [comment]
This is out of scope for this repo. Our goal here will be to provide a framework for writing a custom "Reader" (or similar module) for reading Avalon's specific input format (i.e. a Avalon-specific CSV template). Look for future tickets error reporting and validation of Batch formats.
